BethanysPieShop/Models/Pie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using BethanysPieShop.Utility;
using Microsoft.AspNetCore.Mvc;

namespace BethanysPieShop.Models
{
    public class Pie
    {
        public int PieId { get; set; }

        [Remote("CheckIfPieNameAlreadyExists", "PieManagement", ErrorMessage = "That name already exists")]
        public string Name { get; set; }

        [MaxLength(100)]
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string AllergyInformation { get; set; }
        public decimal Price { get; set; }

        [ValidUrl(ErrorMessage = "That's not a valid URL")]
        public string ImageUrl { get; set; }

        [ValidUrl(ErrorMessage = "That's not a valid URL")]
        public string ImageThumbnailUrl { get; set; }
        public bool IsPieOfTheWeek { get; set; }
        public bool InStock { get; set; }
        public int CategoryId { get; set; }
        public virtual Category Category { get; set; }
        public virtual List<PieReview> PieReviews { get; set; }

        //Specific for Model Binding
        public SugarLevel SugarLevel { get; set; }
        public RecipeInformation RecipeInformation { get; set; }


    }
}

BethanysPieShop/ViewModels/PieViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BethanysPieShop.ViewModels
{
    public class PieViewModel
    {
        public int PieId { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public decimal Price { get; set; }
        public string ImageThumbnailUrl { get; set; }
    }
}

BethanysPieShop/Controllers/PieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using BethanysPieShop.Filters;
using Microsoft.AspNetCore.Mvc;
using BethanysPieShop.Models;
using BethanysPieShop.Utility;
using BethanysPieShop.ViewModels;
using Microsoft.Extensions.Logging;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace BethanysPieShop.Controllers
{
    [PieNotFoundException]
    public class PieController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IPieReviewRepository _pieReviewRepository;
        private readonly HtmlEncoder _htmlEncoder;
        private readonly ILogger<PieController> _logger;

        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository, ILogger<PieController> logger,
            IPieReviewRepository pieReviewRepository, HtmlEncoder htmlEncoder)
        {
            _pieRepository = pieRepository;
            _categoryRepository = categoryRepository;
            _pieReviewRepository = pieReviewRepository;
            _htmlEncoder = htmlEncoder;
            _logger = logger;
        }

        //[Route("AllPies")]
        //[Route("ListOfPies")]
        public ViewResult List(string category)
        {
            IEnumerable<Pie> pies;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                pies = _pieRepository.Pies.OrderBy(p => p.PieId);
                currentCategory = "All pies";
            }
            else
            {
                pies = _pieRepository.Pies.Where(p => p.Category.CategoryName == category)
                   .OrderBy(p => p.PieId);
                currentCategory = _categoryRepository.Categories.FirstOrDefault(c => c.CategoryName == category).CategoryName;
            }

            return View(new PiesListViewModel
            {
                Pies = pies,
                CurrentCategory = currentCategory
            });
        }

        [Route("[controller]/Details/{id}")]
        public IActionResult Details(int id)
        {
            var pie = _pieRepository.GetPieById(id);
            if (pie == null)
            {
                _logger.LogDebug(LogEventIds.GetPieIdNotFound, new Exception("Pie not found"), "Pie with id {0} not found", id);
                //return NotFound();
                //Catch this error using the exception filter
                throw new PieNotFoundException();
            }

            return View(new PieDetailViewModel() { Pie = pie });
        }

        [Route("[controller]/Details/{id}")]
        [HttpPost]
        public IActionResult Details(int id, string review)
        {
            var pie = _pieRepository.GetPieById(id);
            if (pie == null)
            {
                _logger.LogWarning(LogEventIds.GetPieIdNotFound, new Exception("Pie not found"), "Pie with id {0} not found", id);
                return NotFound();
            }

            string encodedReview = _htmlEncoder.Encode(review);

            _pieReviewRepository.AddPieReview(new PieReview() { Pie = pie, Review = encodedReview });

            return View(new PieDetailViewModel() { Pie = pie });
        }

    }
}

BethanysPieShop/Views/Pie/Details.cshtml
@using System.Net
@using System.Threading.Tasks
@model PieDetailViewModel

<div class="thumbnail">
    <img alt="@Model.Pie.Name" src="@Model.Pie.ImageUrl">
    <div class="caption-full">
        <h3 class="pull-right">@Model.Pie.Price</h3>
        <h3>
            <a href="#">@Model.Pie.Name</a>
        </h3>
        <h4>@Model.Pie.ShortDescription</h4>
        <p>@Model.Pie.LongDescription</p>
        <p class="button">
            <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
               asp-route-pieId="@Model.Pie.PieId">Add to cart</a>
        </p>
    </div>
</div>

<h3>Reviews for this pie</h3>

@foreach (var review in @Model.Pie.PieReviews)
{
    @*@Html.Raw(@review.Review)*@
    <div>@WebUtility.HtmlDecode(review.Review) </div>
    <hr />
}

<form asp-controller="Pie" asp-action="Details" method="post" class="form-horizontal" role="form">
    <h4>Write a review</h4>
    <hr />
    <input type="hidden" asp-for="@Model.Pie.PieId" />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Review" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Review" class="form-control" />
            <span asp-validation-for="Review" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Send review" />
        </div>
    </div>

</form>

BethanysPieShop/Views/Pie/List.cshtml
@*@model PiesListViewModel

@ViewBag.CurrentCategory
@foreach (var pie in Model.Pies)
{
    @Html.Partial("PieOverviewSummary", pie)
}*@

<div id="pieDiv">


</div>

@section scripts{

    <script>

        $(document).ready(function () {
            LoadMorePies();
        });

        $(window).scroll(function () {
            if ($(window).scrollTop() == $(document).height() - $(window).height()) {
                LoadMorePies();
            }
        });

        function LoadMorePies() {

            $.ajax({
                type: 'GET',
                url: '/api/PieData',
                dataType: 'json',
                success: function (jsonData) {
                    if (jsonData == null) {
                        alert('no data returned');
                        return;
                    }

                    $.each(jsonData, function (index, pie) {

                        var PieSummarString = '<div class="col-sm-4 col-lg-4 col-md-4"> ' +
                                              '  <div class="thumbnail">' +
                                              '     <img src="' + pie.imageThumbnailUrl + '" alt="">' +
                                              '      <div class="caption">' +
                                              '         <h3 class="pull-right">' + pie.price + '</h3>' +
                                              '         <h3>' +
                                              '             <a href=/Pie/Details/' + pie.pieId + '>' + pie.name + '</a>' +
                                              '         </h3>' +
                                              '         <p>' + pie.shortDescription + '</p>' +
                                              '    </div>' +
                                              '    <div class="addToCart">' +
                                              '        <p class="button">' +
                                              '             <a class="btn btn-primary" href=/ShoppingCart/AddToShoppingCart?pieId=' + pie.pieId + '>Add to cart</a>' +
                                              '         </p>' +
                                              '     </div>' +
                                              '  </div>' +
                                              '</div>';

                        $('#pieDiv').append(PieSummarString);
                    });
                },
                error: function (ex) {
                    alert(ex);
                }
            });
            return false;
        }
    </script>

}

BethanysPieShop/Views/Pie/PieNotFound.cshtml
@if (Model is string)
{
    @Model
}